### ISSUE TITLE
XMPP Support

### ISSUE THREAD

**Issue by vsviridov** [sovereign/sovereign#2]
eJabberd server with postgres auth would fit in nicely

**Comment by flasheater** [comment]
Hi. Personally I like ejabberd more, simply because I already know how to administer it. So suppose I fork sovereign and replace prosody. Could that be merged back here? Is there a way to express alternative roles ?

**Comment by al3x** [comment]
@flasheater You're encouraged to fork and/or modify your particular Sovereign installation. However, we've chosen Prosody because of its easy administration and low memory footprint, so we're unlikely to replace it with Ejabberd.

You may find https://github.com/birkand/ansible-role-lider-ejabberd useful.

**Comment by flasheater** [comment]
Maybe I was not clear enough, but the idea is not to replace prosody, but
offer both.

For example, the xmpp role could have an ejabberd.yml additionally and the
main.yml would either include prosody.yml or ejabberd.yml based on some
variable.

I am asking because I am about to fork sovereign and add ejabberd for my
own purposes and maybe having alternate implementations of roles is
something you are interested in pulling from.

-- Oliver Krylow

**Comment by al3x** [comment]
We've tried to stick to a single option for each service that Sovereign provides. "Curating" the selection of software for running a personal cloud is a large part of the value of Sovereign. Introducing additional choices into the setup process decreases that value, from my perspective. But we'd be happy to link to your alternate implementation from the README or wiki.

**Comment by flasheater** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I can definitely see the value in that. It's more simple and easier to maintain.

However, don't you 'lose out' on many potential contributions as every fork that replaces something gets hard to pull from?

On January 2, 2015 4:14:07 PM CET, Alex Payne <notifications@github.com> wrote:
>We've tried to stick to a single option for each service that Sovereign
>provides. "Curating" the selection of software for running a personal
>cloud is a large part of the value of Sovereign. Introducing additional
>choices into the setup process decreases that value, from my
>perspective. But we'd be happy to link to your alternate implementation
>from the README or wiki.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/al3x/sovereign/issues/2#issuecomment-68533068
-----BEGIN PGP SIGNATURE-----

iQI/BAEBCAApIhxPbGl2ZXIgS3J5bG93IDxva3J5bG93QGdtYWlsLmNvbT4FAlSm
uZcACgkQovQI0wu3odaP2BAAkFhd444zy4P6muMWwvgrhzsq6da4h+WMxS0+WJKR
WVSfwvyDaUma4oO1mVn5REBg5CqESf2pEWkcvWiGriwwkHSNflfYDTr8vaSC0R0+
ERgrfKkIbPcXsiLyJm0Pd5QB23Xm0wahGtChqOb+llD4q1BR8Rv+aqrjf2duH3Z/
luaEG3aCbwZtJ9+I/VbU+BNoYoj8uY2nwdsUITnczYNjmn5N0JCQMtMe/d3y0WrJ
nq+hFem/Eqkcn0siHd/0Lfu8pf5zpOreMkAjxgVnMSBDwYA5j5J53ZxKs8JnoBvf
gcgpwlnA8oAJWpzIItSHCDaGglj+2VbCvjFIzaoZ0N9IHThgb5nG6iQNV9j7q7wA
Fv2yZC4s/IF+rwdm1yH5wbIvtWH9NF1MYBJ6kwdIbJo60H8ix0y7CM0wRQXlrIoq
0TTWQskQhZmjrGBsvXwSZau2VF6InjoahZU9V5RWHK/vN2UVi2p7vDOHMItwmmj+
R6B0LgdnBDhrzo0oCdCw0I0PNj1DUCuk9LQyHu1eN1hIdsXMzAIdvnbKAuYasZBD
tYvPd1h9W0Ipr8/Qf6TFtxXdGhlvXGsneCCHNr/P9ANy3a6bHf2nr6QzOl6h6PoR
ZWp3/D8OKrRte+twcwsz+JDT4A1AKuymiudgGDYsQzM2gYPAIMeqoC+VIoma/ViE
DR0=
=LR8F
-----END PGP SIGNATURE-----
