### ISSUE TITLE
Update Dovecot SSL config

### ISSUE THREAD

**Issue by al3x** [sovereign/sovereign#251]
As per the message in the latest Dovecot debs:

> You already have ssl certs for dovecot.
> However you should move them out of /etc/ssl
> and into /etc/dovecot and update the configuration
> in /etc/dovecot/conf.d/10-ssl.conf accordingly.
> See /usr/share/doc/dovecot-core/README.Debian.gz for details.

**Comment by mikeashley** [comment]
The dovecot documentation seems contradictory.  The README recommends copying the certificates to `/etc/dovecot`.  The [online documentation](http://wiki2.dovecot.org/SSL/DovecotConfiguration) still refers to `/etc/ssl`, also noting that the certificates are read with root permissions before dropping priviliges.  Is a change actually needed?

**Comment by mikeashley** [comment]
We've deviated on how SSL certificates are installed since adding support for Let's Encrypt.  Keys are stored in /etc/letsencrypt/archive and readable only with root permission or by those in the ssl-cert group.  This is documented in DESIGN.md for the role.  It'll need revisited if/when we switch to a packaged version of LE.  In the meantime, I think we're ok on this.
