### ISSUE TITLE
encfs fails

### ISSUE THREAD

**Issue by hhirsch** [sovereign/sovereign#383]
I just want a simple mailserver so I comment everything except for common and mailserver. However it complains at Check for existing encfs and Create encfs. Both fail.
Is there no way to switch it off?

**Comment by lukecyca** [comment]
Please see #120

**Comment by hhirsch** [comment]
I see. So putting all my config files in a location where they clearly don't belong is considered a fix. There is no proper way to make it work with encfs?

TASK [common : Check for existing encfs] ****************************************
fatal: [xxxx]: FAILED! => {"changed": false, "end": "2015-06-09 05:26:10.145517", "stdout": "", "cmd": "ls /encrypted/*", "start": "2015-06-09 05:26:10.132995", "delta": "0:00:00.012522", "stderr": "ls: cannot access /encrypted/*: No such file or directory", "rc": 2, "invocation": {"module_name": "command", "module_args": {"_raw_params": "ls /encrypted/*", "_uses_shell": true}}, "stdout_lines": [], "warnings": []}

TASK [common : Create encfs] ****************************************************
fatal: [xxxx]: FAILED! => {"changed": true, "end": "2015-06-09 05:26:14.001475", "stdout": "Error decoding volume key, password incorrect", "cmd": "printf \"p\nclear\" | encfs /encrypted /decrypted --public --stdinpass && touch /decrypted/test", "start": "2015-06-09 05:26:10.994871", "delta": "0:00:03.006604", "stderr": "", "rc": 1, "invocation": {"module_name": "command", "module_args": {"_raw_params": "printf \"p\nclear\" | encfs /encrypted /decrypted --public --stdinpass && touch /decrypted/test", "_uses_shell": true}}, "stdout_lines": ["Error decoding volume key, password incorrect"], "warnings": []}

**Comment by lukecyca** [comment]
If you are wanting to disable encfs, then #120 is the quickest solution since all of the other configuration assumes those specific filesystem locations. Please understand that sovereign aims to be a one-size-fits-most personal cloud server including email, blog, irc, vpn, etc. If you require a more tailored solution you will have to do some customizing yourself. You are welcome to use our work as a starting point, of course.

If you are ok using encfs, but are asking why it is failing, then that is something we can help you with. If you've simply commented out all the roles in `site.yml` except `common` and `mailserver`, that *should* work. It appears from the output you provided that you used `clear` as your encfs_password. Perhaps encfs requires a longer password.

**Comment by hhirsch** [comment]
I try that. Might as well use sovereign as it was intended. Very fast reply, thank you.

**Comment by hhirsch** [comment]
A longer password did not work. To be fair though. I did run the playbook once before I set the passwords for encfs. So that might have destroyed it.

**Comment by hhirsch** [comment]
What options do I have?

**Comment by lukecyca** [comment]
I'm not sure what is going on. Before I suggest blowing it all away and trying again, let's try a few things...

What distro/version are you running? What VPS service (if any)?

Can you try `rm -rf /decrypted /encrypted` and then running the playbook again?

**Comment by al3x** [comment]
Please reopen if this is still an issue. Default configuration of using encfs seems to work for most users.
