### ISSUE TITLE
SSLUseStapling On in apache config cause problems

### ISSUE THREAD

**Issue by hippich** [sovereign/sovereign#406]
It appears that debian wheezy has apache 2.2.x in their repositories and SSLUseStapling option as available starting 2.4.x.

**Comment by neuhaus** [comment]
Confirmed. For now, please upgrade to Apache 2.4 or remove that option.

**Comment by shaneonabike** [comment]
I added a wiki page for this to help people out. Maybe we could add something to the README also just to flag this or at least tell people to head to the [wiki](https://github.com/sovereign/sovereign/wiki/Apache-Stapling-(Compatibility-only-with-Apache-2.4)) if they are having issues. 



@hippich do you think you could provide more info on the wiki if people want to upgrade their apache. I want to do that but was curious as to whether I needed to upgrade my PHP also. I suspect not right?

**Comment by hippich** [comment]
@shaneonabike, i just removed SSLUseStapling from my configs.

**Comment by sread** [comment]
It seems that based on this [page](https://www.digitalocean.com/community/tutorials/how-to-configure-ocsp-stapling-on-apache-and-nginx) we need to have an SSLStaplingCache:

   SSLStaplingCache shmcb:/tmp/stapling_cache(128000)

and this needs to be defined outside  <VirtualHost></VirtualHost> so it can't go in the existing ssl.conf includes. A conf-available/ssl-stapling-cache.conf file ((a2enconf enabled) worked for me (although the actual stapling fails due to the self-signed cert in the vagrant box).

**Comment by danmilon** [comment]
What @sread said. I run into this issue also. @al3x what is the proposed sollution for jessie? I can send a PR.

**Comment by neuhaus** [comment]
Debian Jessie comes with Apache 2.4 so SSLUseStapling works there.
We should remove it for Debian 7 because it breaks the default.

**Comment by neuhaus** [comment]
Wait, isn't this already fixed since July 16th in commit 1be1afe?

It explicitly checks for wheezy:

    {% if ansible_distribution_release != 'wheezy' %}
        SSLUseStapling On
        SSLStaplingResponderTimeout 5
        SSLStaplingReturnResponderErrors off
    {% endif %}

Please clarify otherwise I will consider this issue to be fixed.

**Comment by sread** [comment]
I believe there are two problems: 

1. Apache < 2.3.3 (fixed as you say)
2. Lack of defined SSLStaplingCache causes apache to fail to start

The confusion is due to my mistake of hijacking the bug (same result, different cause)

**Comment by neuhaus** [comment]
Thanks @danmilon, have you tested it on wheezy and something else?

**Comment by danmilon** [comment]
Jessie only. But the added tasks dont interfere with wheezy so it shouldn't be affected.

**Comment by neuhaus** [comment]
The thing is it's wheezy that's broken so I'd like someone with wheezy to give it a quick test before I merge it.

**Comment by danmilon** [comment]
Well, with wheezy no ssl stapling is configured at all currently.
Previously wheezy was broken because ssl stapling was added in apache 2.4. but 1be1afe fixed that.
And jessie was broken because the ssl stapling was not fully configured (missing ssl stapling cache directive).

Currently ssl stapling is properly configured on jessie (tested)
and it is omitted on wheezy.

BTW I dont see backport of apache for wheezy.

Anyway, someone on wheezy can test whether apache is broken, incl. #430.

**Comment by neuhaus** [comment]
Thanks all!
