### ISSUE TITLE
Create SSL certificates using Let's encrypt

### ISSUE THREAD

**Issue by neuhaus** [sovereign/sovereign#426]
[Let's encrypt](https://letsencrypt.org) is a new free and automated certificate authority that will enter productive mode this month.

I plan to add support for it to sovereign to replace the need for an expensive wildcard certificate, however it will be quite a bit of work so any help is appreciated.

**Comment by masterkorp** [comment]
The link is wrong, correct one is https://letsencrypt.org/

**Comment by tracker1** [comment]
+1 was coming in to suggest the very same...  Will be very cool to have automated letsencrypt SNI setup for the custom domain(s) in question...

**Comment by neuhaus** [comment]
Fixed the link. So, do you guys want to help? :-) Got suggestions regarding which client to use? There is the official one of course (written in python), but there are also alternatives.

**Comment by tracker1** [comment]
If python is already in the dependencies, I'd just go with the default/official client.

**Comment by sread** [comment]
Did a bit of research, since we're not the only ones interested in this. thefinn93 ( https://github.com/thefinn93/ansible-letsencrypt ) ansible role looks like a good starting point, see also ( https://community.letsencrypt.org/t/completely-automated-setup/3121/2 )

**Comment by neuhaus** [comment]
The official client is not very popular because it tries to do too many things.
Here are some simple alternatives:
* https://github.com/kuba/simp_le
* https://github.com/diafygi/acme-tiny/
* https://github.com/xenolf/lego *(needs golang)*
* https://github.com/barosl/letsencrypt-simple
* https://github.com/hlandau/acme.t *(needs golang)*

**Comment by danmilon** [comment]
What do you think the overall architecture should be? I can try to tackle this. All needs to happen in the host where things are being provisioned, right?

One problem I thought of, is that you don't know which roles are activated, thus which domains to ask the certificate for. One solution to that is one certificate for each service.

**Comment by neuhaus** [comment]
The DNS part is outside of the scope of the sovereign project. I.e. the user has to make sure the DNS records are in-place. The playbook should make sure to check a DNS record before trying to create a Let's encrypt certificate.

**Comment by danmilon** [comment]
I'm talking about [SANs](https://en.wikipedia.org/wiki/SubjectAltName). When you ask LetsEncrypt for the cert, if you're going to install one cert for all services, you need to ask for which subdomains the certificate will be valid. LetsEncrypt does not support wildcard certificates.

And there will be a validation for each subdomain you ask, so it needs to work, cant be arbitrary.

That's why you need to know which roles are being provisioned, in order to ask only for them.
Or else have independent certificates for each service.

**Comment by neuhaus** [comment]
In the "common" role we can do the installation of an ACME client.

Then there are two tasks that need to be done for every virtualhost:
1. Get a certificate rightaway so the Apache can start using it.
2. Set up a cronjob for automatic renewal every X days

For now, I suggest we just do it for one role and then find out what the best way is to do it for several roles. There is no way to loop over the roles in ansible from what I've seen.

**Comment by danmilon** [comment]
Okay, so that would be one certificate for each service. Yeah, I don't see any downside to that. When we see that it works flawlessly we can drop self signed certs entirely.

I'll work on that.

**Comment by neuhaus** [comment]
Then there are some non-HTTPS services such as Mail (IMAP and SMTP) and Jabber where we can probably also use the certificates.

The hostnames are currently assigned in the `vars/default.yml` file:

   git.{{ domain }}
   news.{{ domain }}
   read.{{ domain }}

etc.

**Comment by neuhaus** [comment]
Does Let's encrypt support putting all SANs in a single certificate? I hadn't considered that possibility.

**Comment by danmilon** [comment]
Yeah, SANs are for a single certificate.

**Comment by neuhaus** [comment]
OK, that would give us less files to deal with but it's more of a hassle if a site owner changes the roles every other day. 
Getting one certficiate with all SANs would probably requires less changes, it'd be somewhat like a wildcard certificate. We just need to document the steps necessary whenever role that involve certificates are added or removed.

**Comment by neuhaus** [comment]
Regarding ACME client, let's go with https://github.com/kuba/simp_le ?

**Comment by neuhaus** [comment]
If we get rid of all webservers listening on port 80, we can set up a single one that deals with ACME challenges for *all* hostnames.
For all requests other than `/.well-known/acme-challenge/` the webserver can redirect to **https**://`$SERVER_NAME`/ with the original path remaining intact.

**Comment by neuhaus** [comment]
One important thing, the folder /.well-known/acme-challenge/ in the webroot should not be owned by www-data, we don't want certificates at risk whenever www-data is compromised.

**Comment by danmilon** [comment]
1. Yes, I'm using `simp_le` for now.
2. Yes, we can do that with port 80 and apache.
3. We need to also point out that even if you don't include all roles, you need to set up the DNS for all of them, or else lets encrypt will fail.

**Comment by neuhaus** [comment]
Regarding 3.
The ansible script could check which hostnames have been configured in DNS and do the certificate tasks only for those that are pointing to it... and complain about the others. 
Every role could check its own hostname and warn if it isn't configured or pointing elsewhere.

**Comment by danmilon** [comment]
I'm still not decided on single-cert per service vs one with SANs. The first is cleaner and the tedious part (set cron job and apache vhost to handle acme challenges can be written in a modular way and imported from other roles). I'd like to try to do it that way first to see if there are more implications. If it works, are you OK with that?

**Comment by neuhaus** [comment]
I'm fine with either way. I agree that separate certificates are easier to automate.

**Comment by sread** [comment]
I've been thinking about this and agree that webroot auth, simp_le and separate certs is the way to go. Looks like you're off to the races but let me know if I can help.

**Comment by ariddell** [comment]
There's this, already ansibilized: https://github.com/debops/acme-tiny

**Comment by neuhaus** [comment]
I don't see anything related to ansible in that repo...

**Comment by ariddell** [comment]
You're right. I assumed all their repos were ansible repositories.

Here's the issues where they (DebOps) discuss ACME support:
- https://github.com/debops/ansible-pki/issues/30
- https://github.com/debops/ansible-nginx/issues/84

Looks like they're almost there (for nginx)

**Comment by drybjed** [comment]
Hello everyone, developer of [DebOps](http://debops.org/) here. :-) I've written a role that can handle certificates (actually most of the PKI structure) in Ansible and let me tell you one thing - don't do it in pure Ansible, it's unmanageable. Write a script that can do all necessary actions like key/cert generation, install it on the host and use Ansible to configure it an launch all necessary tasks. Just don't put the logic in the role/playbook itself.

I'm currently working on a `acme-tiny`-based implementation of the PKI, with ACME being added to "internal" sets of certificates handled by a set of CAs managed by Ansible Controller, and "external" set of certificates managed by a custom script provided by the user - each set of finished certificates (I call that a "realm") will automatically pick either external, ACME, or internal certs depending on their availability, so that internal hosts not reachable from the Internet can also have certificates. It doesn't really mater what certificates a service uses, as long as the clients have a maching trusted CA certificate, so my goal here is to have a valid set at all times.

As for the support in `nginx` (maybe you could consider switching, hint, hint), it's [already done](https://github.com/debops/ansible-nginx/pull/91) in my `debops.nginx` role. You can also read [notes about the design](https://github.com/debops/ansible-nginx/blob/master/docs/acme-support.rst) to see how it is supposed to work.

**Comment by ariddell** [comment]
Hi @drybjed. Thanks for coming over here to comment.

I've been trying out debops myself and I do like some of the tricks being used to make ansible roles more module (the debops.etc_services is quite nice). On balance, I think it *should* be a model for how to modularize our roles.

I'm not a fan of ``debops.pki``, which is how debops manages certs -- but I take it neither are you @drybjed? How easy would it be to use ``debops.nginx`` and your ``acme`` role without using any other ``debops`` roles? (In particular, sovereign uses ufw (not ferm).)

If we use ACME/Lets-Encrypt we also need to make those certificates available for the mail server -- do I have that right? How complicated will this be?

**Comment by drybjed** [comment]
Hey @ariddell :-) Ironically, Sovereign was one of the catalysts for making DebOps - I just wanted to do it better ;P

Current `debops.pki` available in the `master` branch was my first attempt at making any sort of Public Key Infrastructure, and it shows. It's like a house of cards, you change one thing and everything falls apart. I wrote it almost a year ago, and always planned to redo it after some time, when I found out what worked and what didn't. Now I'm ready to write it again, this time better and easier to control, and with more bells and whistles like ACME.

There is no "DebOps ACME" role, the ACME support will be incorporated into `debops.pki`. The reason is, not all hosts that can be managed by DebOps are expected to be reachable by the Let's Encrypt CA over the Internet, and I still want them to use TLS connections. So the support for different types of certificates will be kind of stackable - by default the internal certificates will be used, if ACME are present they will be preferred, and any external certificates provided by the user via a script will take precedence (think their own company PKI infrastructure).

Don't think of the set of certificates signed by Let's Encrypt as only for the webserver, it's a mistake. X.509 certificates are agnostic. You just need to make sure that you provide them in a standardized location and configure your various services to use them. Coincidentally, that's what `debops.pki` aims to do, to make a stable and known environment for other roles to use certificates. For example path to where certificates are stored is saved as an Ansible local fact, which other Ansible roles can use to configure certificate support in their services. That way, I don't need to worry about `nginx` role maintaining its own set, it just hooks up to `debops.pki` infrastructure if it's present, automatically.

As for using Sovereign with DebOps roles... One issue might be heavy use of role dependencies in roles like `debops.nginx` or similar. I'm currently in the middle of refactoring things to move "hard" role dependencies into [the corresponding playbook](https://github.com/debops/debops-playbooks/tree/master/playbooks/service) of each role - after that you could use them in Sovereign without much issue, apart from handling missing firewall support, for example. But it will take some time, other things like ACME took precedence. You can right now disable `debops.nginx` role dependencies by setting `nginx_dependencies: False` in the Ansible inventory, that way they will be just skipped.

**Comment by ariddell** [comment]
@drybjed very glad to hear about these efforts. I'd love to see `debops` become even more modular.

So it looks like sovereign could get by with a pki role which is lighter than debops's debops.pki. We *do* anticipate that every host using sovereign will be able to talk to the Let's Encrypt ACME server. I think this would allow for a great deal of simplification. Sovereign may be able to get away with a single, simple ``acme`` role.

Perhaps this is a good place to start the modularization it sounds like we all seem to want (#440): a branch/repo of sovereign that just installs nginx (or apache) and fetches a certificate from lets-encrypt. Each role could be its own repo, following debops' example.

**Comment by mikeashley** [comment]
I need to get moving on this before my own site's certificate expires in February.  I submitted pull request #451 for feedback.  Known issues:

1. Stopping/starting apache even if you don't need a certificate is goofy.
2. No story for certificate renewal.

What else am I missing?  Also, I am an Ansible rookie, so suggestions on how to code this better are welcome.

**Comment by neuhaus** [comment]
The pull request #462 (adding Radicale support) would also benefit from a Let's encrypt cert.

**Comment by drybjed** [comment]
The rewrite of `debops.pki` role to make it easier to use and add external and ACME certificate support is partially done in [this PR](https://github.com/debops/ansible-pki/pull/33). In the PR there are instructions for how to use it and debug it if necessary. I'm looking for more people to test the code and find issues. If anybody wants to try it with Sovereign, I would be interested to see the results.

The Ansible role should be self-contained, although it uses resources on Ansible Controller like `bash` and `openssl` which should be in the recent versions.

**Comment by drybjed** [comment]
Welcome, just a quick update. The `debops.pki` role has been updated, you can [grab it from GitHub](https://github.com/debops/ansible-pki), new code is also [available on Ansible Galaxy](https://galaxy.ansible.com/debops/pki/), there's also [excellent documentation](http://docs.debops.org/en/latest/ansible/roles/ansible-pki/docs/). Check it out :-)

**Comment by mikeashley** [comment]
An update from me.  I've gotten good feedback on the drafts of LE support I submitted.  There's agreement to support LE on the jessie branch, so I have LE support on the back burner while we work to get the jessie branch stable.  (Getting closer!)

I used a draft PR to base what I am doing on my own server (wheezy).  It's working fine, and it was nice to avoid paying to re-up my certificate.  I'm glad to be getting stick time with LE before we officially support it.

**Comment by carljm** [comment]
Thanks for your work on this! Really looking forward to seeing it in the Jessie branch. (Kind of holding off on my own sovereign deployment until that happens, actually.) If you can point me to a branch or PR that you think is basically ready, I'd give it a try.

**Comment by hpk42** [comment]
I am also very interested in LE support and ready to try it out as i am setting up a new server with sovereign.

**Comment by ariddell** [comment]
I'll close this since #504 addresses it.
