### ISSUE TITLE
dovecot.index.log permission error

### ISSUE THREAD

**Issue by lukecyca** [sovereign/sovereign#46]
I have a bunch of these errors littering `/var/log/mail.err`:

```
Sep 25 00:20:39 vps1 dovecot: imap(me@lukecyca.com): 
    Error: link(/decrypted/lukecyca.com/me/dovecot.index.log,
    /decrypted/lukecyca.com/me/dovecot.index.log.2) failed: 
    Operation not permitted
```

**Comment by canihavesomecoffee** [comment]
A small bump, but I'm running into exactly the same issue. I think I might have found a discussion which touches the issue we all seem to have: https://www.mail-archive.com/search?l=dovecot@dovecot.org&q=subject:%22Re%3A+Permissions+problem+with+mdbox+maildir%22&o=newest&f=1

Apparently, it would seem that (at least in their & my case), due to the "paranoid" setup of the encfs container, hard links are not allowed, and as such causing the error in dovecot. 

I'm currently trying out this solution (as suggested in that thread):

```
maildir_copy_with_hardlinks = no
```

I hope this helps you guys too (took away too much time to leave this issue just as is)
