### ISSUE TITLE
OpenSSH: client bugs CVE-2016-0777 and CVE-2016-0778 

### ISSUE THREAD

**Issue by fengor** [sovereign/sovereign#464]
Until you are able to patch affected systems, the recommended workaround is to use

    # echo -e 'Host *\nUseRoaming no' >> /etc/ssh/ssh_config

That is, add the option UseRoaming no to your /etc/ssh/ssh_config (or your user's ~/.ssh/config) file, or start your ssh client with -oUseRoaming=no included on the commandline.

We will be updating this article with more information as it becomes available.

UPDATE: This affects OpenSSH versions 5.4 through 7.1.

**Comment by fengor** [comment]
https://github.com/sovereign/sovereign/pull/463

**Comment by neuhaus** [comment]
Thanks for the PR. Some questions:

What happens if the SSH version is too old to understand "UseRoaming"

Isn't this issue fixed by the updated packages that were released already?

When was "becomes" added to Ansible? We should not break backward compatability too quickly here. For example, Ubuntu 14.04 still ships currently has Ansible 1.7.2

**Comment by fengor** [comment]
OpenSSH Releae 5.4 (first affected version) is from 2010-03-07. Anyone using an openssh version that old has major other problems.

The updated Packages should fix the issue yes but i think making sure can't hurt in this case.

The becomes should have been a different pull request my bad. Good Point about the packaged ansible version in distros. I'll revert that change.
