### ISSUE TITLE
Use 'become' instead of 'sudo'

### ISSUE THREAD

**Issue by fengor** [sovereign/sovereign#465]
sudo was deprecated in ansible playbooks in 1.9.

See the deprecation warning in the travis logs.

**Comment by neuhaus** [comment]
Sounds good. Could you provide a PR please?

**Comment by fengor** [comment]
https://github.com/sovereign/sovereign/pull/466

Pull request does not need to be merged at once but can be done when supported distros are updated to ansible 1.9 or greater

**Comment by mikeashley** [comment]
@fengor I'm trying to make sense of the related pull requests but can't verify root cause.  Could you explain how to reproduce the deprecation warnings on one's desktop?  I am not able to do it with either 1.9.3 or 1.9.4 running `ansible-playbook --syntax-check -i hosts site.yml`.  I would like to squash the lint noise we're getting with PRs on the jessie branch at least.

**Comment by mikeashley** [comment]
This has been addressed, right?  Ready to close?

**Comment by fengor** [comment]
can be closed. sorry didnt had time to work on this further.

i don't know if syntax check shows it but the deprecationw arning showed
for me when i normally executed the playbook

On Sun, Mar 13, 2016 at 12:27 PM, Mike Ashley <notifications@github.com>
wrote:

> This has been addressed, right? Ready to close?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sovereign/sovereign/issues/465#issuecomment-195939268>
> .
>



-- 
Friends applaud, the comedy is over. -- Last words of Ludwig von Beethoven

**Comment by mikeashley** [comment]
Ok, I think this is as designed.  On master we are asking for Ansible 1.6+.  If version 1.9.3 or newer is installed, the user will see deprecation warnings.  If someone believes we should use Ansible >= 1.9.3 on master, then let's have an issue for that.
