### ISSUE TITLE
Opendmarc errors

### ISSUE THREAD

**Issue by simontretter** [sovereign/sovereign#497]
On Ubuntu 14.04 and a standard sovereign install, I get this the opendmarc_report.log

> Can't locate DBD/yes.pm in @INC (you may need to install the DBD::yes module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/sbin/opendmarc-import line 22.
Can't locate DBD/yes.pm in @INC (you may need to install the DBD::yes module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/sbin/opendmarc-reports line 27.

It still connects to the database.

**Comment by neuhaus** [comment]
It's a bug in the OpenDMARC 1.2.0+dfsg-1 packaged, fixed in 1.3.0 (or Debian 1.2.0+dfsg-2 which has not yet made it to Ubuntu Trusty).

 * https://sourceforge.net/p/opendmarc/tickets/90/
 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=742447

Could you please open a bug at https://launchpad.net/ubuntu/+source/opendmarc/+bugs ?

**Comment by hpk42** [comment]
Is there a temporary work around? Like installing yes.pm manually or so?

**Comment by neuhaus** [comment]
@hpk42 There is a patch for opendmarc in the bug at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=742447
