### ISSUE TITLE
How is dspam configured for junk mail handling?

### ISSUE THREAD

**Issue by hpk42** [sovereign/sovereign#527]
Running master on a ubuntu 14.04 VPS gives me these in the  mail.log file:
`
Mar 10 07:38:24 Ubuntu-1404-trusty-64-minimal dspam[11588]: Unable to open file for reading: /decryp
ted/dspam/data/merlinux.eu/hpk/hpk.sig/56e0e34713931689415866.sig: No such file or directory
`

Is this a significant problem?  I am particularly asking since i have the feeling dspam so far lets lots of spam through to my inbox.  How can i check that dspam is actually training on my inbox/junk mailboxes properly? 
thanks for any pointers.

**Comment by hpk42** [comment]
and when i run ``dspam_stats`` or ``dspam_train`` as either the dspam or as root user i always get ``unable to attach dspam context``.  This does mean that dspam is not properly working, right?

**Comment by neuhaus** [comment]
Is there really a space in `/decryp ted/`?

**Comment by hpk42** [comment]
nope, sorry, there isn't a space.  By now i found out that i can run ``dspam_train holger@... SPAMDIR/cur INBOXDIR/cur`` and that does something but i still basically basically get lots of spam in my inbox, even the same messages.  Also i found out that i need to check for the ``X-DSPAM-RESULT: Spam`` header in my sieve file instead of the ``X-SPAM-FLAG`` which i found on the web.

Basically my question now is if sovereign configures  dspam/dovecot by default to work out of the box including training messages i move from inbox to junk.

**Comment by neuhaus** [comment]
I'm not very familiar with dspam, hopefully someone else can provide some insight.

**Comment by oskapt** [comment]
By default dspam trains on messages that it passes through as being ham, essentially reinforcing its own conclusion unless told otherwise. There is no provision within the sovereign configuration for telling it otherwise. You can move messages to Junk, but they will stay there. 

I've modified my install of sovereign with files you can find in [this gist](https://gist.github.com/oskapt/0316f402dd3f8ee986f9d40a61713df6)

The steps are:

1. create a new playbook in the `mailserver` role called `local.yml` for local mods
1. add the template for `junk_training.sh` in `templates/`
1. add the two support scripts in `files/`
  * `decrypted_dspam_antispam_update-cut.sh`
  * `decrypted_dspam_antispam_update-filter.sh`

With these items we get the following:

* dynamically extract domains from `/decrypted` by looking for top-level directories owned by `vmail`
* crawl this list every 30 minutes (via cron), looking for users' `Junk` folders
* for every message in `Junk` retrain and move to `Spam`
* if we don't have a `Spam` folder for the user, create one
* if we don't have a `Ham` folder for the user, create one
* for any user with messages in the `Ham` folder, retrain as non-spam and move to `INBOX`
* additionally, go through every day and delete spam older than 30 days for everyone

This works great. I move messages to Junk, and within 30 minutes they're in Spam. If I find a message in Spam that isn't spam, I move it to Ham, and within 30 minutes it reappears in my inbox.

The only issue with this script, also recognized by the author on line 50, is that it moves to INBOX instead of pushing it back through maildrop to go through sieve rules. It hasn't yet become annoying enough for me to fix it. It also doesn't mark messages as read, so my spam folder always shows some number of unread messages. Also not yet annoying enough for me to fix.

`dspam` takes a while (2 weeks or so) to figure out what you consider to be spam, after which it starts working well. Because it self-trains on Ham, you don't have the normal Bayesian issues of also having to train it on what is not spam.

I hope this helps answer your questions about dspam!

**Comment by oskapt** [comment]
Oh - also, the reason you get errors about `unable to attach to dspam context` is because we're not running dspam as a daemon. I don't know what the benefit of doing so might be, but I believe all of the command-line tools for interacting with `dspam` expect to talk to the daemon.

**Comment by shaneonabike** [comment]
I am getting 

`/decrypted/dspam/junk_training.sh: line 19: syntax error near unexpected token `|'
/decrypted/dspam/junk_training.sh: line 19: `domains=({{ domain_list.stdout_lines|join(' ') }})'`

But I want to make sure that I am installing this properly. Did you indicate that all the files should go in the mailserver directory (the appropriate places). I noticed you had a main.yml that I cannot figure out where to put. I had manually added everything first to test it out but I don't think that the domain_list is correct...

**Comment by oskapt** [comment]
* `main.yml` changes are to go at the bottom of `main.yml` in the `mailserver/tasks` directory (I've updated gist to reflect this)
* `domain_list` is derived from the command in the first block of `local.yml` - it looks at the contents of `/decrypted`, filters them by what directories are owned by `vmail` (which theoretically should only be directories corresponding to domains hosted on the system), and stuffs it into the variable `domain_list`. 

If you put these files in manually, `junk_training.sh` won't work. It's a `j2` template that needs to be installed by Ansible. If you want to use it manually, just put something like:
```
domains=(example.com otherdomain.com mydomain.com)
```

If you only have one domain, keep the parentheses and put your single domain inside of it.

Let me know if you have other questions.

**Comment by shaneonabike** [comment]
Of course! Silly me and now this totally works! This should totally be integrated into the main stream it's awesome!

**Comment by neuhaus** [comment]
@oskapt The spam training is a great addition. Could you have a look at PR #617 / issue #611 ? Are you proposing the same thing with your gist?

**Comment by oskapt** [comment]
My gist is for dspam, not rspamd. None of my stuff is useful for rspamd - go with the dovecot antispam plugin instead. It monitors all folders, removes the need for spam/ham/junk, and pushes the training back in. It's definitely the way to go.

**Comment by lukecyca** [comment]
With #617 we now have rspamd training based on users moving messages to Junk.

I believe the last missing piece for a fully-functional auti-spam system is #626, which will cause Sieve to move spammy messages out of the inbox automatically.
