### ISSUE TITLE
Remove encfs in favour of full disk encryption

### ISSUE THREAD

**Issue by jdeluyck** [sovereign/sovereign#559]
Encfs, while handy, is far from ideal, and has several issues as posted on https://en.wikipedia.org/wiki/EncFS. 

Proposal: support full disk encryption, and boot-time dropbear to allow unlocking of the disk via SSH.
(unlock could be done via an expect script from a remote site, in case the server goes down frequently, via cron/...)

Something as stupid as 

    #!/usr/bin/expect -f
    spawn ssh root@targethost
    expect "~ # "
    send "echo -n 'fancykey' >/lib/cryptsetup/passfifo ; exit"
    close 

already does the trick.

**Comment by neuhaus** [comment]
The default scripts provided with Debian 7 and Ubuntu 14.04 for doing this are broken.

There are some alternatives:

* Ext4 encryption (see issue #468)
* [securefs](https://github.com/netheril96/securefs), "a better transparent encryption filesystem"

See also: Solved issue #120 which already makes encfs optional.

**Comment by neuhaus** [comment]
I'd like to keep this out of sovereign at the moment.
Putting the entire machine into an encrypted root partition is something you can do already prior to setting up sovereign.
EncFS is already optional. You are welcome to improve the documentation in this regard.

A PR to use securefs instead of EncFS would be interesting.
