### ISSUE TITLE
rmilter not accepting connections

### ISSUE THREAD

**Issue by lukecyca** [sovereign/sovereign#595]
After upgrading to Jessie, I am not able to get rmilter to work. I get these messages in `/var/log/mail.log`:

```
Sep 28 22:51:57 vps3 postfix/submission/smtpd[11395]: warning: connect to Milter service inet:127.0.0.1:9900: Connection refused
```

I noticed that the rmilter process is still using a unix socket, but from #521 it sounds like the intention is to use a tcp socket.

```
$ lsof
...
rmilter 11399 _rmilter    3w  unix 0xffff88003ac71940      0t0  198290 /run/rmilter/rmilter.sock
```

Perhaps `/etc/rmilter.conf` needs to be specified by ansible. Better yet, perhaps we should put all configuration overrides in `rmilter.conf.local` or `rmilter.conf.d`.

@carljm could you have a look and clarify? I can prep a PR if you can clarify what should be done.

**Comment by lukecyca** [comment]
Confirmed that the following change appears to fix it.

```diff
root@vps3:~# diff /etc/rmilter.conf{.orig,}
5c5
< bind_socket = unix:/run/rmilter/rmilter.sock;
---
> bind_socket = inet:9900@localhost
```

Will wait for comments before submitting a PR to make sure I'm not missing something (I don't feel I understand systemd that well yet).

**Comment by neuhaus** [comment]
So the issue is that postfix running smtpd in a chroot can't reach the rmilter unix domain socket?
UNIX domain socket would be preferable if we can get it to work, it's roughly twice as fast as TCP sockets IIRC.

**Comment by lukecyca** [comment]
> So the issue is that postfix running smtpd in a chroot can't reach the rmilter unix domain socket?

In #521, @carljm explains why he chose to use a TCP socket, which I think is probably fine. At least, that's not what I'm trying to change here.

The issue here is that the configuration for rmilter appears to still try to use the UNIX socket, which is contradictory to the comments in #521, etc.

It's probably a simple fix. I just wanted to run it by @carljm for clarification prior to making the change in case I'm missing something.

**Comment by carljm** [comment]
Sorry, haven't had much time for sovereign recently. I think this is fine. It definitely worked after #521, but that was probably because we were using a socket-triggered service, and that service definition specified the TCP port. I think that has since been removed for other reasons, which probably broke this.

**Comment by lukecyca** [comment]
Thanks @carljm. My fix has been merged so I consider this resolved.

**Comment by neuffer** [comment]
Immediately after installation rmilter is up with the wrong configuration and requires a restart in order to switch from the non-working domain to tcp sockets. Until then all connects to port 9900 will fail.

I don't know enough about Ansible yet to get it to restart process after the configuration of rmilter.
