### ISSUE TITLE
Document how to change passwords

### ISSUE THREAD

**Issue by alexec** [sovereign/sovereign#643]
I can't see anywhere in the documentation how to change your password. I think this is probably a key task?

**Comment by neuhaus** [comment]
Which password in particular? There are many...

**Comment by alexec** [comment]
All of them!

**Comment by neuhaus** [comment]
There is nothing special about Sovereign regarding changing of passwords.
You should refer to the documentation of the particular software.
For UNIX accounts you can use the "passwd" command.

Regarding virtual mail passwords, we don't bundle a tool to administrate them at the moment.
Consider using something like [vea](https://github.com/neuhaus/vea/).

If you can contribute a pull request to improve the documentation in this regard, that would be delightful.

**Comment by der-gee** [comment]
I had issues with selfoss and wallabag and managed to edit both passwords via ssh:

**selfoss:**
- Visit https://news.yourdomain.tld/password and generate your hash.
- Afterwards set the `password` in `/var/www/selfoss/config.ini` to the generated hash.

**wallabag:** (instructions found [here](https://github.com/wallabag/wallabag/issues/1092#issuecomment-74593670), added some details)
- Look up your wallabag salt: `cat /var/www/wallabag/inc/poche/config.inc.php`
- Create a SHA1-hash from your password, login and the salt. You can use: [this generator](http://www.sha1-online.com/). For instance, `passwordloginsalt` gives 1bbc43879ee7fb5c78c8dcefee1f9f31d0ffe4f2. I'll use these credentials in the insert statement below, make sure to use your own ^^ 
- Switch to the postgres user: `su postgres`
- Log into the wallabag db: `psql walabag`
- With `\d` you'll get all tables. To quit the view type `q`
- My users table was clear, but look it up with: `SELECT * FROM users;`
- If empty, add your user with: INSERT INTO users VALUES (1,'login','1bbc43879ee7fb5c78c8dcefee1f9f31d0ffe4f2','login','your@mail.adress'); 
- Otherwise change the existing entry accordingly. Be sure to end your sql-statements with ";"
- You don't have to provide your mail adress.
- Type `\q` to quit psql

Hope this helps some guys having the same issues.

**Comment by neuffer** [comment]
On 23.01.2017 23:53, der-gee wrote:
>
> I had issues with selfoss and wallabag and managed to edit both
> passwords via ssh:
>
> *selfoss:*
>
>   * Visit https://news.yourdomain.tld/password and generate your hash.
>   * Afterwards set the |password| in |/var/www/selfoss/config.ini| to
>     the generated hash.
>
> *wallabag:* (instructions found here
> <https://github.com/wallabag/wallabag/issues/1092#issuecomment-74593670>,
> added some details)
>
>   * Look up your wallabag salt: |cat
>     /var/www/wallabag/inc/poche/config.inc.php|
>   * Create a SHA1-hash from your password, login and the salt. You can
>     use: this generator <http://www.sha1-online.com/>. For instance,
>     |passwordloginsalt| gives
>     1bbc43879ee7fb5c78c8dcefee1f9f31d0ffe4f2. I'll use these
>     credentials in the insert statement below, make sure to use your
>     own ^^
>   * Switch to the postgres user: |su postgres|
>   * Log into the wallabag db: |psql walabag|
>   * With |\d| you'll get all tables. To quit the view type |q|
>   * My users table was clear, but look it up with: |SELECT * FROM users;|
>   * If empty, add your user with: INSERT INTO users VALUES
>     (1,'login','1bbc43879ee7fb5c78c8dcefee1f9f31d0ffe4f2','login','your@mail.adress
>     <mailto:your@mail.adress>');
>   * Otherwise change the existing entry accordingly. Be sure to end
>     your sql-statements with ";"
>   * You don't have to provide your mail adress.
>   * Type |\q| to quit psql
>
> Hope this helps some guys having the same issues.
>

I think it would be a good idea to add this to the wiki. :-)

**Comment by alexec** [comment]
What about a script you could run?

**Comment by der-gee** [comment]
@neuffer I've created said [wiki page](https://github.com/sovereign/sovereign/wiki/Edit-Selfoss-and-Wallabag-credentials).
@alexec Maybe someone more experienced could provide one? I'm not seeing myself doing it, at least any time soon.

**Comment by alexec** [comment]
I think the Wiki page is perfect. 

I plan to change my passwords as part of my set-up (as I'm doing this for security and privacy reasons). I'll update this when I've got instructions.

**Comment by mikeashley** [comment]
Thank you!
