### ISSUE TITLE
encfs security

### ISSUE THREAD

**Issue by sprig** [sovereign/sovereign#71]
Hello,

I'm not sure I understand the point of encfs, or perhaps how it is implemented:

If the machine is considered trusted, then what's the point of encryption (not considering possible loss here like a laptop because it is always remote anyway)?

If the machine is not trusted, it cannot be allowed access to the decryption key, and thus cannot decrypt email, etc.

Is everything here done in-browser/mail client on the fly? I guess not, since I don't know whether such technology exists today, and even so, it probably wouldn't be compatible with search...

Can you please explain either how encfs is used (if I misunderstood something) or its utility (if understood correctly)?

Thanks in advance!

**Comment by neuhaus** [comment]
Note that if you run sovereign on a VPS, the data on disk will be encrypted, however the ISP can run arbitrary commands inside your VPS, accessing it without you having any chance of detecting that or stopping him from doing so.
If you can't trust your ISP 100%, I strongly suggest you use a dedicated server instead of a VPS.
Remember, the ISP may be forced to retrieve data from your VPS against his will.
