### ISSUE TITLE
What package is doing the dkim checking please? (added rspand dkim feedback)

### ISSUE THREAD

**Issue by mannp** [sovereign/sovereign#725]
Looking at this for most of today and can't figure out why my mails are not getting dkim checked.

Not sure if its opendkim as the only error i am getting there is port being refused, but it seems that milter doesn't use that port now?

Or is it rspamd which complains it cannot find a private key. Which seems like it might be the issue but rspamd.conf has no mention of the certs location. It might just be an arc issue....

> 2017-12-06 17:13:17 #23946(normal) <ed15a0>; task; lua_dkim_sign_handler: cannot load dkim key /var/lib/rspamd/arc/domain.arc.key: cannot stat private key /var/lib/rspamd/arc/domain.arc.key: No such file $
> 2017-12-06 17:13:17 #23946(normal) <ed15a0>; task; lua_dkim_sign_handler: cannot load dkim key /var/lib/rspamd/dkim/domain.dkim.key: cannot stat private key /var/lib/rspamd/dkim/domain.dkim.key: No such f$

Any pointers would be really helpful :)

**Comment by mikeashley** [comment]
You're running the latest from `master`?

**Comment by mannp** [comment]
Yes, as of a couple of days ago.

**Comment by mikeashley** [comment]
OpenDKIM is what's used at the moment for DKIM signing, not rspamd.

On the other hand, we've wanted to eliminated OpenDKIM and OpenDMARC.  I've got this fixed in PR #720 pending review.  I'll likely merge it this weekend, or you can grab it now if you want to try it.  I'm using it on my own server.

**Comment by mannp** [comment]
Mmh OK thanks, can't see OpenDKIM even trying to sign anything.

I've spent a few frustrating days on this one with a few things changed to get things running on AWS Ubuntu so will likely wait for your merging into master, if you are doing it this weekend?

I also note the readme still mentions opendkim and dmarc as milters, is that still the case after this merge?

> +Postfix is the MTA, Dovecot the LDA and IMAP server, and the milters
>  +are OpenDKIM, OpenDMARC, and Rspamd.

**Comment by mikeashley** [comment]
No, it's not.  Thanks for catching that; fixed.

**Comment by mannp** [comment]
Ok merged your PR locally and will try it later today, once I have checked my local changes.

**Comment by mannp** [comment]
Ok so first thing; I have merged over my updated local copy which worked for my ubuntu install on aws, so not a fully clean install.

That said your merge went without a hitch and I now have dkim signatures added to my outgoing emails; which is indeed progress from before the merge.

End result for DKIM was a **pass**

How do I test my dmarc as I haven't got this far before :)

Some small items....

1) Note within dmarc.conf for rspamd;

  # report_settings MUST be present
  report_settings {
    # The following elements MUST be present
    # organisation name to use for reports
    **org_name = "Ashley Family";**

2) Out of interest why is there no local.d/dkim_signing.conf, while there is a dmarc and redis.conf?

3) Does it say anywhere that the created pub/priv dkim keys are here -> /var/lib/rspamd/dkim/

**Comment by mikeashley** [comment]
Ah, thanks for the catch on org name.  I fixed it, corrected a configuration file error in dmarc, updated README and pushed again.

For your other feedback:

* There is no `dkim_signing.conf`, because it's not needed.  See the Rspamd documentation online if you are curious.
* The PR updates Sovereign's README to refer to `/var/lig/rspamd/dkim` to get the public key to copy to a DNS record.  The only other documentation of location is the task itself.  Was this not enough?
* I think the web password is anything?
* No particular reason for suggesting 11334.  I'm usually debugging just one thing at a time, so I didn't think about the clash. :)

Thank you for the feedback!

**Comment by mikeashley** [comment]
For verifying DMARC operation, the best I've been able to find is to read the rpsamd log in `/var/log/rspamd` to verify the report generator is running.  For receiving reports, you will get an email if a message comes from your server that fails authentication (although by configuring `p=none`, any such email should not be rejected by the other server).  For my own deployment, I've gotten a couple of these emails over the past few weeks for a couple of emails.  I have not had a chance to investigate.

**Comment by mikeashley** [comment]
@mannp I'm going to go ahead and close this issue.  Please open a specific issue with DMARC or DKIM if you are still having trouble after the latest patches.  Thanks again for the feedback.
