### ISSUE TITLE
Add mail list service

### ISSUE THREAD

**Issue by amedranogil** [sovereign/sovereign#751]
Add optional/core feature for providing mail listing services, like [Mailman](http://list.org/), I personally prefer [Sympa](https://www.sympa.org/), which can also be linked to LDAP groups dynamically creating mail lists from LDAP groups.

**Comment by neuhaus** [comment]
Pull requests welcome!

**Comment by amedranogil** [comment]
I an't no ansemble conoseur, but here is something that might be useful:
https://github.com/sympa-community/sympa-ansible

**Comment by francisco-core** [comment]
Hey! I've been trying to setup [mailtrain](https://mailtrain.org/) it's not for mailing-lists, but rather newsletters. I was trying to set that up, but no luck so far. There is an [ansible configuration](https://github.com/Vaizard/mage-mailtrain), but I did not have success with it.
But it seems to me that this issue is more for a sovereign-organization rather than a sovereign individual. Would there be an interest in setting up a sovereign-organization repo, for doing the same thing but with the necessities of small organizations?

**Comment by neuhaus** [comment]
I'm closing this issue for now. 
We need to focus on keeping the existing features working.
